In [1]:
import numpy as np

- агрегирование 

Агрегирование - вычисление неких сводных показателей

In [2]:
arr_1 = np.random.random(10)
arr_1

array([0.09837916, 0.68862491, 0.78326793, 0.02049048, 0.82538947,
       0.52915712, 0.12417829, 0.88269363, 0.98571716, 0.46649128])

In [4]:
# все ли значения отвечают условию
# имеется ли в массиве значения отвечающие условиям

In [5]:
arr_3 = np.arange(10).reshape((5,2))
arr_3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
np.any(arr_3 > 7, axis=0)

array([ True,  True])

In [7]:
np.any(arr_3 > 7, axis=1)

array([False, False, False, False,  True])

In [9]:
np.any(arr_3 < 5, axis=0)

array([ True,  True])

- маскирование 

In [11]:
arr_4 = np.random.randint(10, size=5)
arr_4

array([2, 6, 3, 8, 2])

In [12]:
# маска - массив с булевыми значениями 
c = arr_4 < 6
c

array([ True, False,  True, False,  True])

In [13]:
arr_4[c]

array([2, 3, 2])

In [18]:
# побитовые операторы & = and, | = or
arr_4 [(arr_4 > 5) & (arr_4 < 8)]

array([6])

In [21]:
arr_4[arr_4 != 8]

array([2, 6, 3, 2])

- прихотливая индексация (fancy indieces)

In [22]:
arr_5 = np.arange(10,20)
arr_5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
# с помощью списка индексов
arr_5[[3,0,5,7]]

array([13, 10, 15, 17])

In [25]:
# с помощью массива индексов
arr_5[np.array([3,0,5,7])]

array([13, 10, 15, 17])

In [26]:
# с помошью прихотливой индексации можно менять форму результирующего массива
fi = np.array(
    [[3,0,1],
    [1,1,5]]

)
arr_5[fi]

array([[13, 10, 11],
       [11, 11, 15]])